development:
    sessions:
        default:
            database: project_manager_development
            hosts:
                - localhost:27017
            options:
    options:
production:
    uri: <%= ENV['MONGOHQ_URL'] %>
