development:
    sessions:
        default:
            database: project_manager_development
            hosts:
                - localhost:27017
            options:
    options:
production: 
    uri: "mongodb://wlglobalcorpheroku:2edca4bf6f2b6626ea706233b1a2f670@troup.mongohq.com:10050/app21654507"

